# Site
name: "Backbone Tours"
title: "Backbone Tours"
description: "Tours and activities around the famous backbone trail in Malibu, CA"
logo: 'assets/images/b.png'
favicon: 'assets/images/b.png'
baseurl:
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ktenzer:
    name: Keith Tenzer
    display_name: ktenzer
    avatar: 
    gravatar: 57390584711754ca675f5786f5e8977a
    email: 
    web: 
    twitter: https://twitter.com/keithtenzer
    description: "Malibu native, mountain biker, hiker, outdoor enthusiast"
  amayer:
    name: Aaron Mayer
    display_name: amayer    
    avatar: 
    gravatar: 
    email: 
    web: 
    twitter: 
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
